apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  # Use Omni Workload Proxying HTTP-only
  server.insecure: "true"
  server.disable.auth: "true"
  server.x.frame.options: ""
